python main.py \
--features_path '/scratch/shared/beegfs/gul/datasets/features/bobsl/featurize-c2281_16f_pad10sec_m8_-15_4_d0.8_-3_22_anon-v0-stride0.25/filtered/' \
--gt_sub_path '/scratch/shared/beegfs/hbull/shared-datasets/bobsl/audio-aligned-corrected/' \
--pr_sub_path '/scratch/shared/beegfs/hbull/shared-datasets/bobsl/audio-aligned-corrected/' \
--gpu_id 0 \
--batch_size 64 \
--n_workers 32 \
--pr_subs_delta_bias 2.7 \
--gt_subs_delta_bias 2.7 \
--fixed_feat_len 20 \
--jitter_location \
--jitter_abs \
--jitter_loc_quantity 3. \
--load_words False \
--load_subtitles True \
--lr 5e-6 \
--save_path 'inference_output/train_coarse_subtitles' \
--train_videos_txt 'data/bobsl_train_1658.txt' \
--val_videos_txt 'data/bobsl_val_32.txt' \
--test_videos_txt 'data/bobsl_test_250.txt' \
--n_epochs 100 \
--concatenate_prior True \
--min_sent_len_filter 0.5 \
--max_sent_len_filter 20 \
--shuffle_words_subs 0.5 \
--drop_words_subs 0.15 \
--resume 'inference_output/word_pretrain/checkpoints/model_0000191709.pt' \
